name: build-docs
on:
  push:
    branches:
      - main
    paths:
      - 'Modules/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build MD file
        run: | 
          npm install js-yaml
          node .github/build-md.js

      - name: Commit file
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            README.md
          commit-message: Update README
          ref: refs/heads/main
  
